[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/", "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/", "aave/=lib/aave/contracts/", "@aave/contracts/=lib/aave-v3-core/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
